### ISSUE TITLE
BusinessCentral.LinterCop.Design.Rule0033AppManifestRuntimeBehind warning on app.json file

### ISSUE THREAD

**Issue by JacobVanAchter-esc** [StefanMaron/vsc-lintercop#15]
Hi,

For every project i get the following warning from Lintercop. I tried reinstalling, manually installing. Setting the execution Policy. 

`Analyzer 'BusinessCentral.LinterCop.Design.Rule0033AppManifestRuntimeBehind' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at BusinessCentral.LinterCop.Design.Rule0033AppManifestRuntimeBehind.FindValueOfFirstValueLessThan(SortedList`2 sortedList, Version version)
   at BusinessCentral.LinterCop.Design.Rule0033AppManifestRuntimeBehind.CheckAppManifestRuntime(CompilationAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass48_1.<ExecuteCompilationActionsCore>b__0() in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 618
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\_work\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1102'`

**Comment by JacobVanAchter-esc** [comment]
moved to BC lintercop
