### ISSUE TITLE
The AL server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

### ISSUE THREAD

**Issue by mt-andrea** [StefanMaron/vsc-lintercop#22]
Hi! 
Yesterday afternoon (07.16. ~14:50) started to get this message:
![image](https://github.com/user-attachments/assets/0a65bcfd-a1c3-4534-9860-9026e954e2f7)
Windowreload, PC restart nothing helps. I even uninstalled the VS code extension but I still get this message.
The output is the following:
![image](https://github.com/user-attachments/assets/20d3a864-215f-4b0e-832a-6c07b0522464)
What sholud I do? Can you help me fix this? I can't do my job untill this isn't fixed.

Thanks in advance.

**Comment by StefanMaron** [comment]
@Arthurvdv do you have an idea what could have caused this?

**Comment by Arthurvdv** [comment]
@mt-andrea thank you for reporting this error. Not sure what's causing this at the moment, but I've added an check in the pre-release version of the LinterCop to try to identify the line of code responsible for this exception.

Could you switch to the pre-release version of the LinterCop look for a LC0000 diagnostic?

![image](https://github.com/user-attachments/assets/e40fc627-275e-4e84-a630-5bd51f98457c)
![image](https://github.com/user-attachments/assets/70096dd8-99ac-4bb3-a97e-aab272e02143)

Best is to close all VS Code windows, where after opening VS Code the pre-release version of the LinterCop should be automatically installed.

Would be great if you could share a small code example from the LC0000 diagnostic to reproduce this error, so I could investigate this.

**Comment by mt-andrea** [comment]
Hi!
@Arthurvdv i got the following output:
Unhandled exception. System.ArgumentException: Reported diagnostic with ID 'LC0000' is not supported by the analyzer (Parameter 'diagnostic')
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.DiagnosticAnalysisContextHelpers.VerifyArguments(Diagnostic diagnostic, Compilation compilationOpt, Func`2 isSupportedDiagnostic) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\DiagnosticAnalysisContextHelpers.cs:line 70
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.OperationAnalysisContext.ReportDiagnostic(Diagnostic diagnostic) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalysisContext.cs:line 985
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.AnalyzeTransferFields(OperationAnalysisContext ctx)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[Error - 9:35:47 AM] The AL server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 9:35:47 AM] Server process exited with code 3762504530.

**Comment by Arthurvdv** [comment]
@mt-andrea Sorry, my bad 😳

I've created an updated version of the pre-release to resolve this. If you still have the setting to pre-release enabled, closing all VS Code windows and after that reopening the project again should now correctly raise the LC0000 rule.

**Comment by mt-andrea** [comment]
@Arthurvdv No problem. Now I have no errors. :D Is this what you wanted to achive? Now it's opening perfectly. THX

**Comment by Arthurvdv** [comment]
@mt-andrea Great to hear you're unblocked and the error is gone now.

I was hoping that there was a LC0000 diagnostic (Info) pointing to something, like the example below.

![image](https://github.com/user-attachments/assets/9090aa92-8044-4503-8dce-66d7ca71fc9b)
 
For now I have temporarily mitigated this with a Try/Catch to suppress this NullReferenceException. Would be great if I could reproduce this, so I could resolve this problem the right way.

I understand if the answer is no, but is there any chance you could share your AL project with me privately?

**Comment by mt-andrea** [comment]
@Arthurvdv hi sorry for the delay i sent a collaborator invite from a private repository idk weather it will work or not

**Comment by Arthurvdv** [comment]
Hi @mt-andrea! Very much appreciated! Unfortunately the project seems incomplete, where I can’t compile the app.

I’ve try’ed to see if I could reproduce the error with the LinterCop, I haven’t been successful so far.

Could it be that the project you have shared is incomplete? I mean, do you also retrieve errors on compiling the app? And do you also experience the same error on the LinterCop for this project?

**Comment by mt-andrea** [comment]
@Arthurvdv  it was exported from NAV my task is to clean up the errors and warnings

**Comment by Arthurvdv** [comment]
@mt-andrea, Is there a possibility you can share the AL Project that does compile without errors?

I've try'ed to investigate with the AL Project you have shared, but without any success unfortunately.

**Comment by Arthurvdv** [comment]
@mt-andrea did you had any chance to look into this?

**Comment by mt-andrea** [comment]
@Arthurvdv I appreciate your patience. The modified code is available in the repository.

**Comment by mt-andrea** [comment]
@Arthurvdv what's happening?
warning AD0001: Analyzer 'BusinessCentral.LinterCop.Design.Rule0024SemicolonAfterMethodOrTriggerDeclaration' threw an exception of type 'System.NullReferenceException' with message 'System.NullReferenceException: Object reference not set to an instance of an object.
   at BusinessCentral.LinterCop.Design.Rule0024SemicolonAfterMethodOrTriggerDeclaration.AnalyzeSemicolonAfterMethodOrTriggerDeclaration(SyntaxNodeAnalysisContext ctx)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass53_1.<ExecuteSyntaxNodeAction>b__1() in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 752
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in X:\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1088'
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.OptionValuesSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.GlobalVarSectionSyntax'.
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.FindGlobalVariables(SyntaxNode node)
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.AnalyzeTransferFields(OperationAnalysisContext ctx)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.OptionValuesSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.GlobalVarSectionSyntax'.
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.FindGlobalVariables(SyntaxNode node)
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.AnalyzeTransferFields(OperationAnalysisContext ctx)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[Info  - 2:42:33 PM] Connection to server got closed. Server will restart.
true
[Error - 2:42:33 PM] Server process exited with code 3762504530.

**Comment by Arthurvdv** [comment]
@mt-andrea Thank you for updating the repository.

Unfortunately, despite my efforts, I haven't been able to reproduce the errors you're encountering. The example project you've provided builds without any errors on my machine. At the moment I have no idea what's going wrong.
Strangely you're now also experiencing issues with the LC0024 rule, where you're the only one now reporting this it seems.

Do you have these problems also on other AL projects?
Do you maybe have another workstation and/or colleagues to try if they also experiencing these issue?

**Comment by Arthurvdv** [comment]
I just thought of something! Could you run the command ```dotnet --info``` in PowerShell and post the output here?

**Comment by mt-andrea** [comment]
dotnet --info

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5
  RID:          win-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by Arthurvdv** [comment]
Unfortunately, I couldn’t reproduce the exception, but I do believe I’ve found a solution for this.

Could you very this with the pre-release [v0.31.2](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.31.2) version of the LinterCop?
