### ISSUE TITLE
LC0014 and PermissionSet caption Length

### ISSUE THREAD

**Issue by IvoMol** [StefanMaron/vsc-lintercop#6]
Analyzer 'BusinessCentral.LinterCop.Design.Rule0014PermissionSetCaptionLength' threw an exception of type 'System.NullReferenceException' with message 'System.NullReferenceException: Object reference not set to an instance of an object.
   at BusinessCentral.LinterCop.Design.Rule0014PermissionSetCaptionLength.CheckPermissionSetNameAndCaptionLength(SymbolAnalysisContext context)
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass49_2.<ExecuteSymbolActionsCore>b__0() in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 658
   at Microsoft.Dynamics.Nav.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info) in D:\a\1\s\source\Prod\Microsoft.Dynamics.Nav.CodeAnalysis\DiagnosticAnalyzer\AnalyzerExecutor.cs:line 1079'

**Comment by StefanMaron** [comment]
"it works on my machine" :D
![image](https://user-images.githubusercontent.com/24838311/194490645-d35e5cd7-7b9e-4234-b3fe-a820afa79437.png)

Can you give me a minimalistic AL Project where this error can be reproduced?

**Comment by IvoMol** [comment]
Clean project has no error.
Probably conflict with "AL Language Tools" extension.
Adding MaxLength = 30 to PermissionSet caption solves the problem.
You can close this issue, thanks.

**Comment by SBiernat** [comment]
Hey Stefan,
The Following Caption is throwing this Error:
Caption = 'My Permissionset', Comment = 'en-US=My Permissionset|de-DE=Mein Berechtigungssatz';
So it looks like, that you are not handling the comment part.
